### ISSUE TITLE
Project Checkpoint 2 

### ISSUE THREAD

**Issue by KSD32** [dylanmore/operation-barbarossa#4]
In looking at your GitHub, I saw the following of project checkpoint 2 complete:
- sources for XML files
- clear directory of files (source-markup and website)

However, there is no documentation present on this Github. Is there any xml documents that have been started? Has a schema been started?

**Comment by dylanmore** [comment]
No, but we will have our completed schemas and XML files for Checkpoint 3. As myself and Professor Bondar discussed, our project may not have a universal schema due to the contents and sources of our project. We are pulling most of our info from the timeline that I posted, and then diving into detail on parts of the timeline with other sources, which is going to make it a bit difficult to create a schema for all of them, so I believe I will have a schema for the timeline, and then one for all of the other sources.

**Comment by ebeshero** [comment]
Okay, so Project Checkpoint 2 didn't see you starting much of your markup yet. Both of you have made commits, but not very many (see GitHub's record: https://github.com/dylanmore/operation-barbarossa/graphs/contributors ). There's a nice splash page present on the webpage (ready for Project checkpoint 2). For Checkpoint 3, we'd like to be helping you with your schema work. As we discussed, there will likely be two schemas, one for the timeline, and one for separate files holding information about the various Barbarossa campaigns. Let's take a look at how the XML structure is shaping up for this next checkpoint.
